---
#
# Include the shared gitlab CI definitions
#
include:
  - project: 'enterprisemodules/gitlab_ci'
    file: 'gitlab-ci.yml'

rac190a_demo_check:
  extends: .demo_check
  variables:
    server: ml-rac190a
  before_script:
    - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > .netrc
    - if [ "$USE_LATEST_MODULES" == "yes" ]; then touch ./use_latest_modules ; fi
    - if [ $PUPPET_VERSION ]; then echo $PUPPET_VERSION > ./puppet_version ; fi
    - mkdir -p modules/software/files
    - cp ~/software/cvuqdisk-1.0.10-1.rpm modules/software/files
    - cp ~/software/LINUX.X64_193000_grid_home.zip modules/software/files
    - cp ~/software/LINUX.X64_193000_db_home.zip modules/software/files
    - cp ~/software/p6880880_190000_Linux-x86-64.zip modules/software/files
    - cp ~/software/p31305339_190000_Linux-x86-64.zip modules/software/files
  script:
    - vagrant up ml-rac190a --no-provision
    - vagrant up ml-rac190b --no-provision
    - vagrant up ml-rac190a --provision
    - vagrant up ml-rac190b --provision
  after_script:
    - vagrant destroy ml-rac190a ml-rac190b --force

rac180a_demo_check:
  extends: .demo_check
  variables:
    server: ml-rac180a
  before_script:
    - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > .netrc
    - if [ "$USE_LATEST_MODULES" == "yes" ]; then touch ./use_latest_modules ; fi
    - if [ $PUPPET_VERSION ]; then echo $PUPPET_VERSION > ./puppet_version ; fi
    - mkdir -p modules/software/files
    - cp ~/software/cvuqdisk-1.0.10-1.rpm modules/software/files
    - cp ~/software/LINUX.X64_180000_grid_home.zip modules/software/files
    - cp ~/software/LINUX.X64_180000_db_home.zip modules/software/files
    - cp ~/software/p6880880_180000_Linux-x86-64.zip modules/software/files
    - cp ~/software/p30899645_180000_Linux-x86-64.zip modules/software/files
  script:
    - vagrant up ml-rac180a --no-provision
    - vagrant up ml-rac180b --no-provision
    - vagrant up ml-rac180a --provision
    - vagrant up ml-rac180b --provision
  after_script:
    - vagrant destroy ml-rac180a ml-rac180b --force

rac122a_demo_check:
  extends: .demo_check
  variables:
    server: ml-rac122a
  before_script:
    - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > .netrc
    - if [ "$USE_LATEST_MODULES" == "yes" ]; then touch ./use_latest_modules ; fi
    - if [ $PUPPET_VERSION ]; then echo $PUPPET_VERSION > ./puppet_version ; fi
    - mkdir -p modules/software/files
    - cp ~/software/linuxx64_12201_grid_home.zip modules/software/files
    - cp ~/software/cvuqdisk-1.0.10-1.rpm modules/software/files
    - cp ~/software/linuxx64_12201_database.zip modules/software/files
    - cp ~/software/p6880880_122010_Linux-x86-64.zip modules/software/files
    - cp ~/software/p30920127_122010_Linux-x86-64.zip modules/software/files
  script:
    - vagrant up ml-rac122a --no-provision
    - vagrant up ml-rac122b --no-provision
    - vagrant up ml-rac122a --provision
    - vagrant up ml-rac122b --provision
  after_script:
    - vagrant destroy ml-rac122a ml-rac122b --force

